class EngilishWord {
  static List<String> ingilizceList = [
    "İnsurance Branch",
    "Overlay",
    "request Focus",
    "rendered",
    "Account",
    "already",
    "Approximate",
    "error-causing",
    "guide",
    "identifier",
    "initialized",
    "Region",
    "transaction",
    "Transaction",
    "abnormally",
    "abort and rollback",
    "skip",
    "continue resolve",
    "Absolute",
    "accept",
    "Access",
    "Account",
    "acknowledge",
    "activity",
    "açıklama",
    "additional",
    "Adjectives",
    "Adverbs",
    "advert",
    "advertisement",
    "age",
    "alan",
    "alfabe",
    "all",
    "allow",
    "always",
    "analysis",
    "Annotate",
    "annotations",
    "answers",
    "appearance",
    "Appearance",
    "Appendices",
    "aspect ratio",
    "assertion",
    "assigned",
    "assignee",
    "assignment",
    "attribute",
    "auth sellingon",
    "authentication",
    "Authentication",
    "authentication Repository",
    "Authentication Status",
    "authorize",
    "badges",
    "Balance",
    "bar",
    "base",
    "Base Options",
    "bearer",
    "Bearer",
    "Benefits Button",
    "better",
    "blank ",
    "Bookmark",
    "bottom sheet",
    "Box Shadow",
    "Branch",
    "brand",
    "Breaking news",
    "breakpoint",
    "brightness",
    "bug",
    "build ",
    "Page",
    " Content",
    "bulk edit",
    "bundles",
    "buyer",
    "buyer city",
    "cache",
    "Cache Extent",
    "Caches",
    "calendar",
    "cambridge unıversty Press",
    "campaign",
    "capture",
    "card",
    "carers",
    "Caret",
    "cart counter",
    "case",
    "category",
    "causing",
    "cell",
    "cells",
    "change",
    "cheaper",
    "check",
    "cheetah",
    "Choose",
    "Circular Chart Annotation",
    "cities",
    "Collapse all",
    "color dot",
    "Column",
    "command palette",
    "comment",
    "commit",
    "compare",
    "Completed",
    "Completer",
    "Component",
    "Confirm merge",
    "confirmation",
    "connected",
    "consts",
    "contact",
    "content",
    "contents",
    "context",
    "Contin",
    "continue",
    "contrast",
    "control affinity",
    "Convert",
    "cook",
    "Count",
    "County",
    "createdAt",
    "credential",
    "creed",
    "currentState",
    "cursor",
    "custom",
    " daily scrum",
    "dark",
    " dark Theme",
    "dashboard",
    "Dashboard",
    "DashboardChart",
    "datasource",
    "datatable",
    "debug",
    "deep",
    "defined",
    "delayed",
    "denied",
    "description",
    "Design",
    "DESTINATIONS",
    "dinner",
    "direction",
    "discount",
    "dismiss",
    "dismissible",
    "display",
    "dispose",
    "distraction",
    "divider",
    "done",
    "due date",
    "Duplicate",
    "Easy Debounce",
    "edit",
    "edition",
    "education",
    "Elementary",
    "elevation",
    "email Verified",
    "encode",
    "end point",
    "endpoint",
    "Enump",
    "environment",
    "exam",
    "exceeded",
    "exception",
    "exceptions",
    "excessive",
    "exclude",
    "exists",
    "Expected",
    "EXPENSE",
    "Export",
    "Extend",
    "extension",
    "extensions",
    "extract",
    "face",
    "factory",
    "fade duration",
    "Failed",
    "field",
    "Find",
    "finishing",
    "firma işlem takibi",
    "flex",
    "flexible",
    "Floating",
    "Focus color",
    "Focus Scope",
    "footer",
    "Force",
    "forget",
    "forgot",
    "frames",
    "Freelance",
    "future",
    "Future",
    "future",
    "await",
    "gender",
    "Good to see you back!",
    "GridView",
    "handler",
    "has Been Pressed",
    "has error",
    "help",
    "helpers",
    "hesaplama",
    "hızlı teslimat",
    "Highlight",
    "History",
    "hover",
    "IdSelection",
    "Illustrations",
    "Incorrect use of",
    "ınspect",
    "Instance",
    "Integrations",
    "Interfaceler",
    "ınvalid",
    "Invalid",
    "Invalidate",
    "Invalidate caches / restart",
    "Is Dense",
    "identifier",
    "implement",
    "import",
    "in Basket Company",
    "inactive Track Color",
    "include",
    "incorrect",
    "İndent",
    "indicator",
    "infinity",
    "information",
    "İnherit",
    "initial Route",
    "initial Binding",
    "initialEntries",
    "initialRoute",
    "instance",
    "instance",
    "instant location",
    "instituted",
    "interceptor",
    "İnteresting",
    "introduced",
    "inundated",
    "invalidated",
    "invite",
    "invoice",
    "invoked ",
    " is Always Shown",
    " is Dismissible",
    "isDense",
    "İsempty"
        "issue",
    "issues",
    "isuncheck",
    "items",
    "jump to",
    "jump to source",
    "Jump to source",
    "Keep out",
    "keep when reformatting",
    "keymap",
    "Last",
    "late",
    "layoutbuilder",
    "leading",
    "Less",
    "ligatures",
    "light",
    "line spacing",
    "Lines",
    "listen",
    "log",
    "logged",
    "Logged",
    "logger",
    "Logout",
    "loose",
    "macros",
    "Manage",
    "Map Entry",
    "module",
    "Movies",
    "Multi Select",
    "mute",
    "navigation",
    "need to",
    "no environment",
    "  No issues",
    " No issues found!",
    "no suggestion",
    "noktalama işaretleri",
    "notification",
    "Notification Card",
    "notifications",
    "  null safety",
    "occurrence",
    "offer",
    "optimize",
    "options",
    "Order Count",
    "order Sale Result Per Seller",
    "overflow",
    "override",
    "owner name",
    "Ödeme Durumu",
    "paginated",
    "panel",
    "parents",
    "Path",
    "pattern",
    "paused on exception",
    "per",
    "Per",
    "per page",
    "performing",
    "pharmacy",
    "place",
    "Plain",
    "poem",
    "power",
    "preposition",
    "present",
    "present simple",
    "Presentation",
    "Presenter",
    "Previous",
    "product",
    "product Sale info Count",
    "provinces",
    "Pull",
    "query Parameters",
    "question",
    "questionnaire",
    "reauthenticate",
    "receiver ",
    "recording",
    "recover",
    "recursively",
    "Redo",
    "Refactoring",
    "refresh tree",
    "register",
    " Regular Expressions",
    "reject",
    "relevant",
    "reload",
    "Reload",
    "Reload  all from disk",
    "Remote",
    "Rename",
    "render flex",
    "replace",
    "Replace",
    "replacement",
    "repo",
    "repository",
    "Repository",
    "reputation",
    "Request",
    "required",
    "Resort",
    "resource",
    "Respon",
    "response",
    "responsive",
    "restore",
    "result",
    "Result",
    "resume",
    "Retry Password",
    "Reverse",
    "revert",
    "review",
    " right now",
    "rollback",
    "  Rollback",
    "  Root",
    "  round",
    "row Count",
    "safety",
    "sale",
    "Samples",
    "Satış Yetkilendirmesi",
    "scheme",
    "Scratch",
    "secondary",
    "seconds",
    "secret",
    "selecct widget mode",
    "Self",
    "seller",
    "Semantics",
    "severe",
    "severity",
    " SfC circular Chart",
    "shape",
    "show",
    "Show inspection description",
    " Show Quick fixes",
    "shrink",
    "shrink Wrap",
    "shrinkWrap",
    "side bar",
    "sidebar",
    "sightseeing",
    " sign in",
    "sign up",
    "Sign up",
    "sipariş",
    "Slot",
    "slow animations",
    "slow animations",
    "show guidelines",
    "show beselines",
    " highlight repaints",
    "higjlight oversized repaints",
    "highlight oversized images",
    "  expand all",
    "slow animations",
    " show guidelines",
    "show beselines",
    "highlight repaints",
    "higjlight repaints",
    "  highlight oversized images",
    "sort",
    "Sort",
    " sort ascending",
    "source",
    "spacer",
    "Spacer",
    "spaces",
    " Splash Screen View",
    "spread Radius",
    "square",
    "Square",
    "State",
    "station",
    "Structurally",
    "structure",
    "Study guide",
    "suggestion",
    "Support",
    "supported",
    "switch",
    "tabs",
    "Talking",
    "tall",
    "tanımlama",
    "target",
    "task",
    "tax",
    "team",
    "ternary",
    "teslimat",
    "text",
    "thickness",
    "Thickness",
    "Throw",
    "tight",
    "Tilecolor",
    "Toggle",
    "token",
    " Toolbar Height",
    " top secret",
    "TRACER",
    "Tracking",
    "transaction",
    "transaction tracking",
    " transitionDuration",
    "travel",
    "trust",
    "tutorial",
    "unconditionally",
    "underline",
    "Undo",
    "unexpected",
    " unexpected  null value",
    "unknown ",
    "authenticated",
    "signed up",
    "Unselect",
    "unselectedItem ",
    "Usages",
    "utilities",
    "uts number",
    "Uzaktan",
    "validation",
    "variable",
    "vergi",
    "verification",
    "verify",
    "vertical",
    "view",
    "visible",
    "visual",
    "visual  guides",
    "visualdensity",
    "waiting",
    "watch",
    "wave clipper",
    "weather",
    "weather",
    "wipe",
    "with",
    "without VirtualBox",
    "word",
    "word",
    "Word order",
    "wrapping",
    "wrapping ve braces",
    "yavaş",
    "yep",
    "**********************************************",
    'encouragement',
    'confused',
    'pure',
    'offended',
    'tasted',
    'sachet',
    'Forehead',
    'expose',
    'talent,',
    'siblings',
    'kazanıyorsun',
    'residential',
    'Deal',
    'enterpreneur',
    'silent',
    'target',
    'casually browsing',
    'Flexible ',
    'immediately',
    'luckly',
    'honestly',
    'redo',
    'dripper',
    'lost',
    'hall',
    'decide',
    'cruel',
    'under',
    'copywriters',
    'sneak out',
    'window dressing',
    'they sell media at a 15% markup',
    'shakedown',
    'markup',
    'mysterious',
    'ignoring',
    'ourselves',
    'embarrassed',
    'awful',
    'blushes',
    'browsing',
    'narrow',
    'wetter',
    'poisoning',
    'poisioning',
    'ptomaine',
    'proctor and gamble',
    'aside',
    'caugtht',
    'chase',
    'winners',
    'in a distraction',
    'wrapped',
    'admission',
    'begging',
    'dodged',
    'rubber cement',
    'fumes',
    'to go on like that about yourself',
    'on like that about yourself',
    'raised',
    'manners',
    'confide',
    'stoned',
    'forthcoming',
    'nerves',
    'divorce',
    'purses',
    'mirror',
    'do you ever have that when your hands go numb',
    'then',
    'than',
    'which can really ruin your trip',
    'worst',
    'aspect',
    'opinion',
    'definitly',
    'reviews',
    'sore',
    'swollen sores',
    'swollen',
    'sensitive',
    'worse',
    'bitten',
    'bugs',
    'low-quality',
    'thus',
    'took a backpacking',
    'backpacking',
    'disappointed',
    'thought',
    'boss',
    'elsewhere',
    'worth',
    'magic',
    'charming',
    'whore',
    'specific',
    'campaign',
    'campaing',
    'camping',
    'presentitial',
    'reconsider',
    'afterglow',
    'ı get it',
    'reassurance',
    'smell',
    'happines',
    'witnessed',
    'poisonous',
    'cure',
    'grow',
    'plant',
    'sunshine',
    'seeds',
    'repellent',
    'insect',
    'breed',
    'identical',
    'cereal',
    'invention',
    'opportunity',
    'exactly',
    'competitors',
    'neither',
    'claims',
    'cancer',
    'healts',
    'favor',
    'bright spot',
    'rifles',
    'insane',
    'hell',
    'dangerous',
    'simply say',
    'quickly',
    'preparation',
    'several',
    'trip',
    'way back',
    'tied',
    'talk out',
    'innovative',
    'reputation',
    'obviously',
    'afford',
    'whether',
    'whatever',
    'suppose',
    'sales',
    'ever',
    'lowest',
    'wall',
    'kind',
    'responsible',
    'even',
    'fact',
    'abuse',
    'warn',
    'spread knees',
    'being practical',
    'possibility',
    'judge',
    'nervous',
    'reason',
    'contraceptive pills',
    'chart',
    'pretty terrific',
    'terrific',
    'terrefic',
    'scream',
    'regards',
    'Plumber',
    'enough',
    'stick',
    'scratch',
    'ridiculous',
    'exact opposite',
    'supposed',
    'powerful',
    'wish',
    'death',
    'postulated',
    'war',
    'label',
    'crossbones',
    'skull',
    'honest',
    'you better find out',
    'fitht',
    'overdo',
    'goals',
    'take care',
    'for the time being',
    'aisle',
    'across',
    'mistakes',
    'avoid',
    'lead',
    'fair',
    'probably',
    'brain',
    'around',
    'creative',
    'judding',
    'Readers digest says',
    'digest',
    'tragedy',
    'tobacco weevil',
    'tobacco weevil comes',
    'brand',
    'habit',
    'reminds',
    'handle',
    'intensive',
    'efficient',
    'scalable',
    'effortlessly',
    'anxcious',
    'before having any effect',
    'initiated',
    'certain',
    'somebody',
    'attracts',
    'Tides',
    'Thousands',
    'worn out',
    'shattered',
    'wrecked',
    'exhausted',
    'determines',
  ];
}
