class TurkishWord {
  static List<String> turkceList = [
    'Sigorta Şubesi',
    'Kaplama',
    'Odaklanma isteği',
    'işlenmiş',
    'Hesap',
    'çoktan',
    'Yaklaşık',
    'hataya neden olan',
    'kılavuz',
    'tanımlayıcı.',
    'başlatıldı.',
    'Bölge',
    'işlem',
    'İşlem',
    'anormal:',
    'iptal et ve geri al',
    'atlamak',
    'çözmeye devam et',
    'Mutlak',
    'kabul',
    'Erişim',
    'hesap',
    'kabul etmek',
    'aktivite',
    'explanation',
    'ek',
    'Sıfatlar',
    'Zarflar',
    'reklam',
    'İlan',
    'yaş',
    'area',
    'alphabet',
    'herşey',
    'izin vermek',
    'her zaman',
    'analiz',
    'açıklama ekle',
    'ek açıklamalar',
    'Yanıtlar',
    'görünüm',
    'Dış görünüş',
    'Ekler',
    'en boy oranı',
    'iddia',
    'atanmış',
    'atanan',
    'Görev',
    'bağlanmak',
    'yetkilendirme',
    'kimlik doğrulama',
    'kimlik doğrulama',
    'kimlik doğrulama Deposu',
    'Kimlik Doğrulama Durumu',
    'yetki vermek',
    'Rozetler',
    'Denge',
    'Çubuk',
    'temel',
    'Temel Seçenekler',
    'taşıyıcı',
    'taşıyıcı',
    'Avantajlar Düğmesi',
    'daha iyi',
    'boşluk',
    'Yer imi',
    'Alt tabaka',
    'Kutu Gölge',
    'Dal',
    'marka',
    'Flaş Haber',
    'kırılma noktası',
    'parlaklık',
    'böcek',
    'inşa etmek',
    'Sayfa',
    'içerik',
    'toplu düzenleme',
    'Paketler',
    'alıcı',
    'alıcı şehir',
    'önbellek',
    'Önbellek Kapsamı',
    'Önbellekler',
    'takvim',
    'Cambridge Unıversty Basın',
    'kampanya',
    'ele geçirmek',
    'kart',
    'bakıcılar',
    'Şapka',
    'sepet sayacı',
    'durum',
    'kategori',
    'neden olan',
    'hücre',
    'hücreler',
    'değiştirmek',
    'daha ucuz',
    'Kontrol',
    'çita',
    'Seçmek',
    'Dairesel Grafik Açıklaması',
    'şehirler',
    'Hepsini Daralt',
    'renkli nokta',
    'Sütun',
    'komut paleti',
    'yorum',
    'işlemek',
    'karşılaştırmak',
    'Tamamlanmış',
    'Tamamlayıcı',
    'Bileşen',
    'Birleştirmeyi onayla',
    'Onayla',
    'bağlı',
    'sabitler',
    'İletişim',
    'içerik',
    'içindekiler',
    'bağlam',
    'içerir',
    'devam et',
    'zıtlık',
    'kontrol afinitesi',
    'Dönüştürmek',
    'pişirmek',
    'Miktar',
    'ilçe',
    'oluşturuldu',
    'Kimlik',
    'inanç',
    'şu anki durum',
    'imleç',
    'özel',
    'günlük koşuşturma',
    'karanlık',
    'karanlık Tema',
    'Gösterge Paneli',
    'Gösterge Paneli',
    'PanoGrafik',
    'veri kaynağı',
    'veri tablosu',
    'hata ayıklama',
    'derin',
    'tanımlanmış',
    'gecikmiş',
    'reddedildi',
    'tanım',
    'Tasarım (değiştir | kaynağı değiştir)',
    'HEDEFLER',
    'akşam yemeği',
    'yön',
    'indirim',
    'Reddet',
    'görevden alınabilir',
    'Görüntüle',
    'elden çıkarmak',
    'dikkati başka yöne çekme',
    'bölücü',
    'tamamlamak',
    'bitiş tarihi',
    'Çiftleme',
    'Kolay Geri Dönme',
    'Düzenle',
    'baskı',
    'Eğitim',
    'İlköğretim',
    'yükseklik',
    'E-posta Doğrulandı',
    'kodlamak',
    'bitiş noktası',
    'uç nokta',
    'numaralandırma',
    'Çevre',
    'sınav',
    'aşıldı',
    'istisna',
    'istisnalar',
    'aşırı',
    'hariç tutmak',
    'var',
    'Beklenen',
    'GİDER',
    'İhracat',
    'Uzat',
    'uzantı',
    'uzantılar',
    'Ayıkla',
    'yüz',
    'fabrika',
    'solma süresi',
    'Arızalı',
    'alan',
    'Bul',
    'Bitiricilik',
    'company transaction tracking',
    'esnek',
    'esnek',
    'Yüzer',
    'Odak rengi',
    'Odak Kapsamı',
    'altbilgi',
    'Güç',
    'unutmak',
    'Unuttun',
    'çerçeveler',
    'serbest',
    'gelecek',
    'Gelecek',
    'gelecek',
    'beklemek',
    'Cinsiyet',
    'Seni tekrar görmek güzel!',
    'Izgara Görünümü',
    'işleyici',
    'basıldı',
    'hata var',
    'Yardım',
    'yardımcılar',
    'calculation',
    'fast delivery',
    'Vurgulamak',
    'Tarih',
    'üzerine gelmek',
    'Kimlik Seçimi',
    'İllüstrasyonlar',
    'yanlış kullanımı',
    'incelemek',
    'Misal',
    'Entegrasyonlar',
    'Arayüzleyici',
    'geçersiz',
    'Geçersiz',
    'Geçersiz kılmak',
    'Önbellekleri geçersiz kıl / yeniden başlat',
    'Yoğun',
    'tanımlayıcı',
    'uygulamak',
    'ithalat',
    'Sepet Şirketinde',
    'etkin olmayan Parça Rengi',
    'Dahil etmek',
    'yanlış.',
    'Girinti',
    'gösterge',
    'sonsuzluk',
    'bilgi',
    'miras',
    'ilk Rota',
    'ilk Bağlama',
    'ilkGirişler',
    'başlangıç rotası',
    'misal',
    'örnek',
    'anlık konum',
    'kurumsal',
    'önleyici',
    'İlginç',
    'tanıtıldı',
    'su altında',
    'geçersiz',
    'Davet et',
    'fatura',
    'çağrıldı',
    'Her Zaman Gösterilir',
    'reddedilebilir',
    'Yoğun',
    'Boş',
    'sorun',
    'sorunlar',
    'işaretini kaldırmak',
    'öğeler',
    'atlamak',
    'kaynağa atla',
    'Kaynağa atla',
    'Dışarıda tutmak',
    'yeniden biçimlendirirken sakla',
    'tuş haritası',
    'Son',
    'geç',
    'düzen oluşturucu',
    'lider',
    'Daha az',
    'bitişik harfler',
    'ışık',
    'satır aralığı',
    'Çizgiler',
    'dinlemek',
    'kayıt',
    'günlüğe kaydedildi',
    'günlüğe kaydedildi',
    'ağaç kesicisi',
    'Çıkış Yap',
    'gevşetmek',
    'makrolar',
    'Yönet',
    'Harita Girişi',
    'modül',
    'Filmler',
    'Çoklu seçim',
    'sesini kapatmak',
    'navigasyon',
    'gerek',
    'çevre yok',
    'Sorun yok',
    'Sorun bulunamadı!',
    'öneri yok',
    'punctuation',
    'bildiri',
    'Bildirim Kartı',
    'bildirimler',
    'sıfır güvenlik',
    'oluşum',
    'teklif',
    'optimize etmek',
    'seçenekler',
    'Sipariş Sayısı',
    'Satıcı Başına Satış Sonucu sipariş',
    'taşma',
    'geçersiz kılmak',
    'sahibinin adı',
    'Payment status',
    'sayfalandırılmış',
    'panel',
    'ebeveynler',
    'Yol',
    'Desen',
    'istisnada duraklatıldı',
    'başına',
    'Başına',
    'Sayfa başına',
    'performans',
    'eczane',
    'yer',
    'Sade',
    'şiir',
    'güç',
    'edat',
    'mevcut',
    'geniş zaman',
    'Sunum',
    'Sunucu',
    'Önceki',
    'ürün',
    'ürün Satış bilgisi Sayı',
    'iller',
    'Çek',
    'sorgu parametreleri',
    'soru',
    'anket',
    'yeniden doğrulamak',
    'alıcı',
    'kayıt',
    'kurtarmak',
    'tekrarlı',
    'Yeniden yap',
    'yeniden düzenleme',
    'ağacı yenile',
    'Kayıt ol',
    'Düzenli ifadeler',
    'reddetmek',
    'ilgili',
    'Tekrar yükle',
    'Tekrar yükle',
    'Tümünü diskten yeniden yükle',
    'Uzak',
    'Adını değiştirmek',
    'esnek hale getirmek',
    'değiştir',
    'Değiştir',
    'değiştirme',
    'depo',
    'depo',
    'Depo',
    'itibar',
    'İstek',
    'gereklidir',
    'Dinlenme tesisi',
    'kaynak',
    'yanıt',
    'cevap',
    'duyarlı',
    'onarmak',
    'sonuç',
    'Sonuç',
    'sürdürmek',
    'Şifreyi Yeniden Dene',
    'Tersine çevirmek',
    'geri almak',
    'gözden geçirmek',
    'şu anda',
    'geri alma',
    'geri alma',
    'Kök',
    'yuvarlak',
    'satır sayısı',
    'Emniyet',
    'satış',
    'Örnekler',
    'Sales Authorization',
    'şema',
    'Kaşımak',
    'ikincil',
    'saniye',
    'gizli',
    'widget modunu seç',
    'Kendisi',
    'satıcı',
    'anlambilim',
    'şiddetli',
    'ciddiyet',
    'SfC dairesel Tablosu',
    'şekil',
    'göstermek',
    'Denetim açıklamasını göster',
    'Hızlı düzeltmeleri göster',
    'küçültmek',
    'küçültmek',
    'küçültmek',
    'yan çubuk',
    'kenar çubuğu',
    'Gezi',
    'kayıt olmak',
    'üye olmak',
    'kaydol',
    'order',
    'yuva',
    'yavaş animasyonlar',
    'yavaş animasyonlar',
    'yönergeleri göster',
    'sınırları göster',
    ' yeniden boyamaları vurgula',
    'büyük boy yeniden boyamalar',
    'büyük boyutlu resimleri vurgula',
    'hepsini genişlet',
    'yavaş animasyonlar',
    'yönergeleri göster',
    'sınırları göster',
    'yeniden boyamaları vurgula',
    'yeniden boyamalar',
    'büyük boyutlu resimleri vurgula',
    'çeşit',
    'Çeşit',
    'artan sıralama',
    'kaynak',
    'aralayıcı',
    'ara parçası',
    'boşluklar',
    'Açılış Ekranı Görünümü',
    'yayılma yarıçapı',
    'Meydan',
    'Meydan',
    'Durum',
    'istasyon',
    'Yapısal olarak',
    'yapı',
    'Çalışma Rehberi',
    'öneri',
    'Destek',
    'desteklenen',
    'değiştirmek',
    'sekmeler',
    'konuşmak',
    'uzun boylu',
    'describing',
    'hedef',
    'görev',
    'vergi',
    'takım',
    'üçlü',
    'delivery',
    'Metin',
    'kalınlık',
    'Kalınlık',
    'Atmak',
    'sıkı',
    'çini rengi',
    'Aç/Kapat',
    'jeton',
    'Araç Çubuğu Yüksekliği',
    'çok gizli',
    'İZLEYİCİ',
    'izleme',
    'işlem',
    'işlem takibi',
    'geçiş süresi',
    'yolculuk',
    'güven',
    'öğretici',
    'koşulsuz olarak',
    'altını çizmek',
    'Geri alma',
    'beklenmedik',
    'beklenmeyen boş değer',
    'Bilinmeyen',
    'kimliği doğrulanmış',
    'kaydoldu',
    'Seçimi kaldır',
    'seçilmemişÖğe',
    'Kullanımlar',
    'araçlar',
    'uts numarası',
    'Afar',
    'doğrulama',
    'değişken',
    'tax',
    'doğrulama',
    'Doğrulayın',
    'dikey',
    'görüş',
    'gözle görülür',
    'görsel',
    'görsel kılavuzlar',
    'görsel yoğunluk',
    'beklemek',
    'izlemek',
    'dalga kesme makinesi',
    'hava Durumu',
    'hava Durumu',
    'silip süpürmek',
    'ile birlikte',
    'VirtualBox olmadan',
    'kelime',
    'kelime',
    'Kelime sırası',
    'sarma',
    'sarma ve parantez',
    'slow',
    'Evet',
    "******************",
    'teşvik',
    'Şaşkın',
    'saf',
    'gücenmiş',
    'tadı',
    'poşet',
    'Alın',
    'ortaya çıkarmak',
    'Yetenek,',
    'Kardeşler',
    'you are earning',
    'yerleşim',
    'Anlaşmak',
    'girişimci',
    'sessiz',
    'hedef',
    'gelişigüzel tarama',
    'Esnek,',
    'hemen,',
    'şans eseri',
    'gerçekten',
    'yeniden yapmak',
    'damlatıcı',
    'kayıp',
    'salon',
    'karar vermek',
    'zalim',
    'altında',
    'metin yazarları',
    'gizlice',
    'vitrin dekorasyonu',
    'medyayı %15 kar marjıyla satıyorlar',
    'sarsılmak',
    'işaretleme',
    'gizemli',
    'görmezden gelmek',
    'kendimizi',
    'mahçup',
    'berbat',
    'kızarır',
    'tarama',
    'dar',
    'daha ıslak',
    'zehirlenme',
    'zehirlenme',
    'ptomain',
    'gözetmen ve kumar',
    'kenara',
    'yakalanmış',
    'kovalamak',
    'kazananlar',
    'dikkat dağınıklığı içinde',
    'sarılmış',
    'kabul',
    'dilenme',
    'atlatmak',
    'kauçuk tutkalı',
    'dumanlar',
    'kendin hakkında böyle devam etmek',
    'kendin hakkında böyle',
    'kabarık',
    'Töre',
    'güvenmek',
    'taşlanmış',
    'gelecek',
    'sinirler',
    'boşanmak',
    'cüzdanlar',
    'ayna',
    'Ellerin uyuştuğunda bunu hiç yaşadın mı?',
    'sonra',
    'hariç',
    'bu gerçekten seyahatinizi mahvedebilir',
    'en kötüsü',
    'Görünüş',
    'fikir',
    'kesinlikle',
    'yorumlar',
    'yara',
    'şişmiş yaralar',
    'şişmiş',
    'duyarlı',
    'daha kötüsü',
    'ısırılmış',
    'böcekler',
    'Düşük kalite',
    'Böylece',
    'sırt çantasıyla gezmek',
    'sırt çantasıyla gezmek',
    'hüsrana uğramış',
    'düşünce',
    'patron',
    'başka yerde',
    'değer',
    'büyü',
    'büyüleyici',
    'fahişe',
    'özel',
    'kampanya',
    'kampanya',
    'kamp yapmak',
    'güncel',
    'yeniden gözden geçirmek',
    'gün batımı sonrası kızıllık',
    'anladım',
    'güvence',
    'koku',
    'mutluluk',
    'tanık',
    'zehirli',
    'Çare',
    'büyümek',
    'bitki',
    'gunes isigi',
    'tohumlar',
    'itici',
    'böcek',
    'doğurmak',
    'özdeş',
    'Mısır gevreği',
    'icat',
    'fırsat',
    'Kesinlikle',
    'rakipler',
    'hiç biri',
    'iddialar',
    'Yengeç Burcu',
    'sağlık',
    'iyilik',
    'parlak nokta',
    'tüfekler',
    'inanılmaz',
    'cehennem',
    'tehlikeli',
    'basitçe söyle',
    'hızlı bir şekilde',
    'hazırlık',
    'birkaç',
    'seyahat',
    'dönüş yolu',
    'bağlı',
    'konuşmak',
    'yenilikçi',
    'itibar',
    'açıkça',
    'gücü yetmek',
    'ikisinden biri',
    'her neyse',
    'sanmak',
    'satış',
    'durmadan',
    'en düşük',
    'duvar',
    'tür',
    'sorumlu',
    'Bile',
    'hakikat',
    'taciz',
    'uyarmak',
    'dizleri yaymak',
    'pratik olmak',
    'olasılık',
    'yargıç',
    'gergin',
    'sebep',
    'doğum kontrol hapları',
    'Çizelge',
    'oldukça müthiş',
    'müthiş',
    'korkunç',
    'çığlık',
    'Saygılarımızla',
    'plumber',
    'yeterli',
    'Çubuk',
    'kaşımak',
    'saçma',
    'tam zıttı',
    'sözde',
    'güçlü',
    'Dilek',
    'ölüm',
    'varsayılmış',
    'savaş',
    'etiket',
    'kemikler',
    'kafatası',
    'dürüst',
    'öğrensen iyi olur',
    'kavga',
    'abartmak',
    'hedefler',
    'kendine dikkat et',
    'şu an için',
    'koridor',
    'karşısında',
    'hatalar',
    'önlemek',
    'öncülük etmek',
    'adil',
    'muhtemelen',
    'beyin',
    'etrafında',
    'yaratıcı',
    'yargılamak',
    'Okuyucu özeti diyor',
    'sindirmek',
    'trajedi',
    'tütün böceği',
    'tütün böceği geliyor',
    'marka',
    'alışkanlık',
    'hatırlatıyor',
    'üstesinden gelmek',
    'yoğun',
    'verimli',
    'ölçeklenebilir',
    'zahmetsizce',
    'endişeli',
    'herhangi bir etkiye sahip olmadan önce',
    'başlatılan',
    'belirli',
    'birisi',
    'çekiyor',
    'Gelgit',
    'binlerce',
    'Yıpranmış',
    'parçalanmış',
    'harap',
    'yorgun',
    'belirler',
  ];
}
